config/routes.rb
Rails.application.routes.draw do

  # 管理者用 URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    get 'search' => 'searches#search'
    resources :users, only: [:index, :show, :edit, :update]
  end

  # 会員用 URL /users/sign_in ...
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "user/registrations",
    sessions: 'user/sessions'
  }

  # ゲストログイン
  devise_scope :user do
    post 'user/guest_sign_in' => 'user/sessions#guest_sign_in'
  end

  scope module: :user do
    root to: 'homes#top'
    get 'about' => 'homes#about'
    get 'mypage' => 'users#show', as: 'mypage'
    get 'mydata/edit' => 'users#edit', as: 'myedit'
    patch 'mydata' => 'users#update', as: 'myupdate'
    get 'cats/new' => 'post_images#new', as: 'new_post_image'
    post 'cats' => 'post_images#create'
    get 'cats' => 'post_images#index', as: 'post_images'
    get 'cats/:id' => 'post_images#show', as: 'post_image'
    delete 'cats/:id' => 'post_images#destroy', as: 'destroy_post_image'
    get 'unsubscribe' => 'users#unsubscribe'
    patch 'users/withdraw'
    delete 'post_images/:post_image_id/favorites' => 'favorites#destroy', as: 'post_image_destroy_favorites'
    post 'post_images/:post_image_id/favorites' => 'favorites#create', as: 'post_image_favorites'
    delete 'post_images/:post_image_id/post_comments/:id' => 'post_comments#destroy', as: 'post_image_destroy_post_comments'
    post 'post_images/:post_image_id/post_comments' => 'post_comments#create', as: 'post_image_post_comments'
    get 'search' => 'searches#search'
    get 'search_genre' => 'post_images#search_genre'
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :post_images
  has_many :favorites, dependent: :destroy
  has_many :post_comments, dependent: :destroy

  # ユーザー名は一意でないといけない
  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true

  # ゲストユーザーの名前とメールアドレスとパスワードは自動作成
  def self.guest
    find_or_create_by!(name: "guestuser", email: "guest@example.com") do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "guestuser"
    end
  end

  # 投稿ユーザー名で検索して、そのユーザーの投稿を一覧表示する
  def self.user_name_like(content)
      PostImage.joins(:user).where("name LIKE ?", "%" + content + "%")
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @users = User.page(params[:page]).per(20)
  end

  def show
    @user = User.find(params[:id])
    # .order(created_at: :desc)で投稿を新着順に表示
    @post_images = @user.post_images.order(created_at: :desc).page(params[:page]).per(10)
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to admin_user_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :is_deleted)
  end

end

app/controllers/user/confirmations_controller.rb
# frozen_string_literal: true

class User::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/user/favorites_controller.rb
class User::FavoritesController < ApplicationController

  def create
    @post_image = PostImage.find(params[:post_image_id])
    favorite = current_user.favorites.new(post_image_id: @post_image.id)
    favorite.save
  end

  def destroy
    @post_image = PostImage.find(params[:post_image_id])
    favorite = current_user.favorites.find_by(post_image_id: @post_image.id)
    favorite.destroy
  end

end

app/controllers/user/homes_controller.rb
class User::HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/user/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class User::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/user/passwords_controller.rb
# frozen_string_literal: true

class User::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/user/post_comments_controller.rb
class User::PostCommentsController < ApplicationController

  def create
    @post_image = PostImage.find(params[:post_image_id])
    @post_comment = PostComment.new(post_comment_params)
    @post_comment.user_id = current_user.id
    @post_comment.post_image_id = @post_image.id
    @post_comment.save
  end

  def destroy
    PostComment.find(params[:id]).destroy
    @post_image = PostImage.find(params[:post_image_id])
  end

  private

  def post_comment_params
    params.require(:post_comment).permit(:comment)
  end

end

app/controllers/user/post_images_controller.rb
class User::PostImagesController < ApplicationController
  
  def new
    @post_image = PostImage.new
    @user = current_user
    @genres = Genre.all
  end

  def create
    @post_image = PostImage.new(post_image_params)
    @post_image.user_id = current_user.id
    if @post_image.save
      redirect_to post_images_path
    else
      @genres = Genre.all
      render :new
    end
  end

  def index
    # .order(created_at: :desc)で投稿を新着順に表示
    @post_images = PostImage.order(created_at: :desc).page(params[:page]).per(12)
  end

  def show
    @post_image = PostImage.find(params[:id])
    @post_comment = PostComment.new
  end

  def destroy
    @post_image = PostImage.find(params[:id])
    @post_image.destroy
    redirect_to post_images_path
  end

  def search_genre
    @post_image = PostImage.new
    # .order(created_at: :desc)で投稿を新着順に表示
    @post_images = PostImage.search(params[:keyword]).order(created_at: :desc).page(params[:page]).per(12)
  end

  private

  def post_image_params
    params.require(:post_image).permit(:image, :title , :caption, :genre_id)
  end

end

app/controllers/user/registrations_controller.rb
# frozen_string_literal: true

class User::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/user/searches_controller.rb
class User::SearchesController < ApplicationController
  before_action :authenticate_user!

  def search
    @model = params[:model]
    @content = params[:content]
    # .order(created_at: :desc)で投稿を新着順に表示
    @records = if @model == "user"
                User.user_name_like(@content).order(created_at: :desc)
               elsif @model == "post_image"
                PostImage.title_like(@content).order(created_at: :desc)
               elsif @model == "genre"
                Genre.genre_name_like(@content).order(created_at: :desc)
               end
    @records = @records.page(params[:page]).per(12)
  end

end

app/controllers/user/sessions_controller.rb
class User::SessionsController < Devise::SessionsController
  before_action :user_state, only: [:create]

  # ゲストログイン機能
  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to post_images_path
  end

  protected

  def user_state
    @user = User.find_by(email: params[:user][:email])
    return if !@user
    if @user.valid_password?(params[:user][:password]) && @user.is_deleted == true
      redirect_to new_user_registration_path, alert: "退会済みのユーザーです。"
    end
  end

end

app/controllers/user/unlocks_controller.rb
# frozen_string_literal: true

class User::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/user/users_controller.rb
class User::UsersController < ApplicationController
  # ユーザーがログインしているかどうか
  before_action :authenticate_user!
  # ゲストユーザーはユーザー編集、退会機能はなし
  before_action :ensure_guest_user, only: [:edit, :unsubscribe]

  def show
    @user = current_user
    # .order(created_at: :desc)で投稿を新着順に
    @post_images = @user.post_images.order(created_at: :desc).page(params[:page]).per(12)
    # お気に入りリストの表示
    favorites = Favorite.where(user_id: current_user.id).pluck(:post_image_id)
    # インスタンス変数 = Kaminari.paginate_array(配列).page(params[:page]).per(12)にすることでページネーションを表示できた
    @favorite_list = Kaminari.paginate_array(PostImage.order(created_at: :desc).find(favorites)).page(params[:page]).per(12)
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update(user_params)
      redirect_to mypage_path
    else
      render :edit
    end
  end

  # 退会確認画面
  def unsubscribe
  end

  # 退会処理
  def withdraw
    @user = current_user
    @user.update(is_deleted: true)
    reset_session
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end

  # ログインしているのがゲストユーザーだったら
  def ensure_guest_user
    @user = current_user
    if @user.name == "guestuser"
      redirect_to post_images_path
    end
  end

end

app/helpers/user/favorites_helper.rb
module User::FavoritesHelper
end

app/helpers/user/post_comments_helper.rb
module User::PostCommentsHelper
end

app/helpers/user/searches_helper.rb
module User::SearchesHelper
end

app/helpers/user/users_helper.rb
module User::UsersHelper
end

app/views/user/users/edit.html.erb
<div class="container">
  <h2>ユーザー情報編集</h2>
    <%= form_with model: @user, url: myupdate_path, local: true do |f| %>
    <table>
      <tr>
        <td class="pt-3"><%= f.label :ユーザー名 %></td>
        <td class="pt-3"><%= f.text_field :name, autofocus: true, class: "form-control" %></td>
      </tr>
      <tr>
        <td class="pt-3"><%= f.label :メールアドレス %></td>
        <td class="pt-3"><%= f.email_field :email, autofocus: true, autocomplete: "email", class: "form-control" %></td>
      </tr>
      <tr>
        <td class="pt-4"><%= f.submit "変更内容を保存", class: "btn btn-md" %></td>
      </tr>
    </table>
    <% end %>
    <br>
    <%= link_to "退会する", unsubscribe_path, class: "btn btn-md", style: "background-color: #ff6347;" %>
</div>

app/views/user/users/show.html.erb
<div class="container">
  <!--ログインしているユーザー名がゲストユーザーじゃなかったらマイページを表示-->
  <% if current_user.name != "guestuser" %>
    <div class="ribbon">
      <h2>マイページ</h2>
    </div>
      <div class="row">
        <div class="col-3">
          <p>ユーザー名<br><%= @user.name %></p>
          <p>メールアドレス<br><%= @user.email %></p>
          <%= link_to "会員情報変更", myedit_path, class: "btn btn-md" %>
        </div>
        <div class="photo-list col-4">
          <h3 class="list-title">投稿一覧</h3><br>
            <div class="d-flex flex-wrap" style="align-items: baseline;">
            <% @post_images.each do |post_image| %>
            <div>
              <%= link_to post_image_path(post_image.id) do %>
                <%= image_tag post_image.get_image(90,90), class: "cat-photo" %>
              <% end %>
              <p><%= post_image.post_comments.count %>コメント</p>
            </div>
            <% end %>
            </div>
            <%= paginate @post_images %>
        </div>
        <div class="col-1"></div>
        <div class="photo-list col-4">
          <h3 class="list-title">お気に入りリスト</h3><br>
          <% if @favorite_list.present? %>
            <div class="photo-index">
              <% @favorite_list.each do |post_image| %>
              <div class="photo-hover">
                <%= link_to post_image_path(post_image.id) do %>
                <%= image_tag post_image.get_image(90,90), class: "cat-photo" %>
                <% end %>
                <p><%= truncate(post_image.title, length:7) %></p>
              </div>
              <% end %>
            <% end %>
            </div>
            <%= paginate @favorite_list %>
        </div>
      </div>
  <% else %>
    <p>マイページ機能は会員でないとご利用できません。</p>
    <p>ログアウトしてから会員登録をしてください。</p>
  <% end %>
</div>

app/views/user/users/unsubscribe.html.erb
<div class="container">
  <div class="ribbon">
    <h2>退会確認画面</h2>
  </div>
    <div class="row pt-4">
      <p>退会するとマイページにアクセスできなくなり、投稿・コメント機能・お気に入り機能がご利用できなくなります。</p>
      <p>投稿した写真やコメント履歴は削除されません。</p>
    </div>
    <div class="row pt-4">
      <div class="col-2"></div>
      <div class="col-4">
        <%= link_to "退会する", users_withdraw_path, method: :patch,
            data: {confirm: "本当に退会しますか？"}, class: "btn btn-md", style: "background-color: #ff6347;" %>
      </div>
      <div class="col-4">
        <%= link_to "退会しない", mypage_path, class: "btn btn-md" %>
      </div>
      <div class="col-2"></div>
    </div>
</div>